[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-play-scraper>=1.2.7",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]
